services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:5050
      - SPOTIFY_API_URL=https://api.spotify.com/v1
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      - SERVER_PORT=5050
      - DATABASE_URL=jdbc:postgresql://db:5432/vibesbased
      - POSTGRES_USER=vibesbased
      - POSTGRES_PASSWORD=vibesbased
      - FRONTEND_BASE_URL=http://localhost:3000
      - SPOTIFY_AUTH_URL=https://accounts.spotify.com
      - SPOTIFY_AUTH_REDIRECT=http://localhost:5050/auth/callback
      - LASTFM_API_URL=http://ws.audioscrobbler.com/2.0
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vibesbased
      - POSTGRES_USER=vibesbased
      - POSTGRES_PASSWORD=vibesbased
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
